### ISSUE TITLE
NRE when creating DTOs from EF-generated files

### ISSUE THREAD

**Issue by daiplusplus** [yohney/dto-generator#2]
I installed the 1.2 version of the extension, which is what's available on the VS Extensions listing.

I have a Database-first EF6 model with each Entity class existing in its own T4-generated `.cs` file.

I right-clicked on such a file and told it to generate the DTO in another project and gave the DTO the same name as the original entity instead of the auto-generated name (e.g. "Foo" instead of "FooDTO"), after clicking OK I got this error message:

> ```
>    ---------------------------
>    Microsoft Visual Studio
>    ---------------------------
>    An exception has occurred
> 
>    Object reference not set to an instance of an object.
>    ---------------------------
>    OK   
>    ---------------------------
> ```

I get the error regardless of what name I choose the DTO.

Also, interestingly, the Destination Project drop-down list shows the same project twice, but not all projects.

**Comment by yohney** [comment]
Hi @Jehoel , thank you for your feedback.
I have not tested thoroughly on EF6 DB-First model, so I'll have to look into this and get back to you with details.

**Comment by yohney** [comment]
@Jehoel I have submitted an update to Visual Studio gallery. Please give it a try and let me know if the issue is fixed.
