### ISSUE TITLE
Non-nullables assign null in SelectorExpression

### ISSUE THREAD

**Issue by msawczyn** [yohney/dto-generator#3]
Thanks for the project -- this is turning out to be quite a time-saver! An issue, though: please check the nullability of an assignment in the SelectorExpression. I'm getting things like

`OwnerId = p.Owner != null ? p.Owner.Id : null`

when OwnerId is a straight int, not an int?. To simplify, the ternary could output

`OwnerId = p.Owner != null ? p.Owner.Id : default(TYPE)`

where `TYPE` is the target type (in this case, `default(int)`) and all would be excellent.

Thanks again.

**Comment by yohney** [comment]
Glad to hear you like the plugin!

I'll fix this issue in a day or two.

**Comment by yohney** [comment]
@msawczyn new version is online, please try it out.
