### ISSUE TITLE
Wrong namespaces in .NET Core

### ISSUE THREAD

**Issue by n00bje** [yohney/dto-generator#4]
GetPossibleProjects() includes a ..NETCoreApp,Version=v1.1 or ..NET Framework 4.6.2 suffix for every .NET Core project in the solution. 'Classic' .NET projects show as expected.

This causes the DTOs to have the wrong namespace and a "using unknown;" statement.

![image](https://cloud.githubusercontent.com/assets/6150967/21932394/ad25c320-d9a0-11e6-9f59-fd140118cd55.png)

**Comment by yohney** [comment]
Hey,

This should be fixed in version 1.5. Dto location dropdown will show same as before, but generated namespaces should be OK now.
