### ISSUE TITLE
Report the DataAnnotations from Entities

### ISSUE THREAD

**Issue by Gwenou** [yohney/dto-generator#6]
Hi,

In the generation of the DTO there is no option to report the DataAnnotations of the entity to the DTO. (Sample [Requiered]  [StringLength(200)] ...)
The validator in MVC.net are based on those DataAnnotation. Without them it do not work.
Thoses Dataannotations are in properties.AttributeLists from syntaxTree.

I have develop it on my side if you want than I add this option (with a checkbox in the second screen) in your code, please add me as contributor.

**Comment by yohney** [comment]
Hey!

I added you as a collaborator. Create a pull request, so I'll check it out.

Thank you for your effort!

**Comment by Gwenou** [comment]
The pull request "Preserve data annotations" is ready for review.
